project:
  type: website
  output-dir: docs
website:
  title: "Matteo Manente"
  navbar:
    background: "#a00414"
    foreground: light
    left:
      - text: "Psychologist | PhD Candidate"
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: resources.qmd
        text: Materials
      - href: cv.qmd
        text: CV
      - href: contacts.qmd
        text: Contacts

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
